version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3.11

python:
    install:
      - requirements: docs/rtd_requirements.txt
      - requirements: docs/requirements.txt
      - method: setuptools
        path: .
    system_packages: false
