# See also:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

branches:
  only:
    - master
    - stable

max_jobs: 4

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda38-x64"
      CONDA_PY: "38" 
      ARCH: '64'
    - PYTHON: "C:\\Miniconda37-x64"
      CONDA_PY: "37"
      ARCH: '64'

build: false

install:
  # set up conda Python
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels conda-forge
  # note: it may become necessary to pin versions of conda/conda-build
  - conda install -yq conda conda-build

test_script:
  #- "%CMD_IN_ENV% activate base"
  #- "%CMD_IN_ENV% python --version"
  #- "%CMD_IN_ENV% python -c \"import struct; print(struct.calcsize('P') * 8)\""
  #- "%CMD_IN_ENV% conda build --quiet ci\\conda-recipe"
  - activate base
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - conda build --quiet ci\conda-recipe
