name: "Unit tests"
on:
  pull_request:
    branches:
      - master
      - stable
  push:
    branches:
      - master
    tags:
      - "v*"
  schedule:
    - cron: "20 5 * * *"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test_suite:
    runs-on: ${{ matrix.OS }}-latest
    name: "Unit Tests"
    strategy:
      matrix:
        CONDA_PY:
          - 3.9
          - 3.8
          - 3.7
        OS: ["ubuntu"]
        MDTRAJ: ["mdtraj-release"]
        INSTALL_WITH: ["pip"]
        include:
          - CONDA_PY: 3.9
            OS: "ubuntu"
            MDTRAJ: "mdtraj-dev"
            INSTALL_WITH: "pip"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.CONDA_PY }}
      - name: "Install dependencies"
        env:
          INSTALL_WITH: ${{ matrix.INSTALL_WITH }}
        run: |
          if [ "$INSTALL_WITH" = "pip" ]; then
            source ci/pip-install/install_requirements.sh
            pip install -U -e ci/pip-install/testing_requirements.txt
          elif [ "$INSTALL_WITH" = "conda" ]; then
            echo "TODO -- fill this in"
          else
            echo "Bad value for INSTALL_WITH: $INSTALL_WITH"
            exit 1
          fi
      - name: "Install MDTraj development version (pip)"
        if: ${{ matrix.MDTRAJ }} == "mdtraj-dev"
        run: pip install --upgrade --force-reinstall -r ci/pip-install/mdtraj_dev.txt
      - name: "Install optional extras (pip)"
        if: ${{ matrix.MDTRAJ }} == "mdtraj-dev"
        run: pip install -r optional_installs.txt
      - name: "Install contact_map"
        run: pip install -e .
      - name: "Versions"
        env:
          INSTALL_WITH: ${{ matrix.INSTALL_WITH }}
        run: |
          $INSTALL_WITH list
      - name: "Autorelease check"
        run: python autorelease_check.py
      - name: "Tests"
        env:
          PY_COLORS: "1"
        run: |
          python -c "import contact_map"
          py.test -vv --cov=contact_map --cov-report xml
      - name: "Report coverage"
        if: ${{ github.event }} != "schedule"
        run: bash <(curl -s https://codecov.io/bash)
